import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalHeader from "@/components/global/header";
import { SmoothScrollProvider } from "@/utils/smoothscrollProvider";
import CustomCursor from "@/components/global/custom-cursor";
import Noise from "@/components/global/noise";
import Preloader from "../components/global/preloader";
import ReactLenis from "@studio-freight/react-lenis";
import Lenis from "@/components/global/lenis";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} antialiased overflow-x-hidden`}>
				<Lenis>
					<Noise />
					<Preloader />
					<GlobalHeader />
					<CustomCursor />
					{children}
				</Lenis>
			</body>
		</html>
	);
}
